In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df =pd.read_csv("inshorts data preprocessed.csv")

In [3]:
df.head()

,Subject,Headline_lemma,Short_lemma
0,Politics,stopped entering studio time arnab,tv news anchor arnab goswami said told could p...
1,Entertainment,new trailer justice league released,new trailer upcoming superhero film justice le...
2,Entertainment,touch right shilpa shinde sexual harassment,television actress shilpa shinde opening claim...
3,Politics,antiromeo squad must trouble consenting youth ...,uttar pradesh chief minister yogi adityanath v...
4,Politics,romeo juliet welcome delhi aap minister,apparent jibe ups antiromeo squad delhi touris...

In [4]:
df.shape

(25196, 3)

In [5]:
 vectorizer = TfidfVectorizer()

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
df['Subject'].unique()

array(['Politics', 'Entertainment', 'Sports', 'Business', 'Science'],
      dtype=object)

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
enc =OrdinalEncoder()

In [10]:
X =df[['Subject']]

In [11]:
enc.fit(X)

OrdinalEncoder()

In [12]:
enc.categories_

[array(['Business', 'Entertainment', 'Politics', 'Science', 'Sports'],
       dtype=object)]

In [13]:
df['Subejct_encoded']=enc.transform(df[['Subject']])

In [14]:
df.head()

,Subject,Headline_lemma,Short_lemma,Subejct_encoded
0,Politics,stopped entering studio time arnab,tv news anchor arnab goswami said told could p...,2.0
1,Entertainment,new trailer justice league released,new trailer upcoming superhero film justice le...,1.0
2,Entertainment,touch right shilpa shinde sexual harassment,television actress shilpa shinde opening claim...,1.0
3,Politics,antiromeo squad must trouble consenting youth ...,uttar pradesh chief minister yogi adityanath v...,2.0
4,Politics,romeo juliet welcome delhi aap minister,apparent jibe ups antiromeo squad delhi touris...,2.0

In [15]:
df['Subejct_encoded'].unique()

array([2., 1., 4., 0., 3.])

We are going to build three options
1.) Predicting only through Headline
2.) Predicting only through Short
3.) Combining the two

In [16]:
X1 = df['Headline_lemma']

In [17]:
y=df['Subejct_encoded']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.33, random_state=42)

In [19]:
tf= TfidfVectorizer()

In [20]:
tf.fit(X_train)

TfidfVectorizer()

In [21]:
train_tf_first = tf.transform(X_train)

In [22]:
tf.get_feature_names()

['aa',
 'aadat',
 'aadhaar',
 'aadhaarlinked',
 'aadmi',
 'aag',
 'aah',
 'aahaa',
 'aaina',
 'aaj',
 'aakash',
 'aam',
 'aamir',
 'aamirs',
 'aane',
 'aankda',
 'aankhen',
 'aap',
 'aapna',
 'aaps',
 'aaraah',
 'aaradhya',
 'aarah',
 'aarti',
 'aasha',
 'aashiq',
 'aashiqui',
 'aata',
 'aave',
 'aawaazepunjab',
 'aawazepunjab',
 'aayog',
 'ab',
 'abandon',
 'abandoned',
 'abbas',
 'abbasmustan',
 'abbington',
 'abbott',
 'abd',
 'abducted',
 'abdul',
 'abdullah',
 'abdullahi',
 'abe',
 'abha',
 'abhas',
 'abhay',
 'abhijeet',
 'abhimanyu',
 'abhinav',
 'abhinetri',
 'abhishek',
 'abhiyaan',
 'abhiyan',
 'ability',
 'able',
 'abled',
 'abmillion',
 'abnormal',
 'aboard',
 'abolish',
 'abolished',
 'abolishes',
 'abolishing',
 'abort',
 'aborted',
 'abortion',
 'abraham',
 'abram',
 'abroad',
 'absconding',
 'absence',
 'absent',
 'absenteeism',
 'absolute',
 'absolutely',
 'absolved',
 'absorb',
 'absorbs',
 'abu',
 'abuse',
 'abused',
 'abuser',
 'abusing',
 'abusive',
 'abvp',
 'ac',
 'academic',
 'academy',
 'acb',
 'accel',
 'accelerator',
 'accent',
 'accept',
 'acceptable',
 'accepted',
 'accepting',
 'accepts',
 'access',
 'accessory',
 'acche',
 'accident',
 'accidental',
 'accidentally',
 'accommodation',
 'accomplice',
 'accord',
 'according',
 'accosting',
 'account',
 'accountable',
 'accountant',
 'accounted',
 'accuracy',
 'accurate',
 'accusation',
 'accuse',
 'accused',
 'accuser',
 'accuses',
 'accusing',
 'acer',
 'achanta',
 'achieve',
 'achieved',
 'achievement',
 'achieves',
 'aci',
 'acid',
 'ackerley',
 'acknowledging',
 'acoustic',
 'acquire',
 'acquires',
 'acquisition',
 'acquittal',
 'acquitted',
 'acre',
 'acrobatic',
 'across',
 'act',
 'acted',
 'actelion',
 'acting',
 'action',
 'activated',
 'activation',
 'active',
 'activist',
 'activity',
 'actor',
 'actordriven',
 'actress',
 'actual',
 'actually',
 'ad',
 'adam',
 'adani',
 'adanis',
 'adapt',
 'adapted',
 'adapting',
 'adapts',
 'adarsh',
 'adb',
 'add',
 'adda',
 'added',
 'addict',
 'addiction',
 'additional',
 'additive',
 'addon',
 'address',
 'adele',
 'adelie',
 'adhia',
 'adhm',
 'adhyayan',
 'adhyayen',
 'adi',
 'adidas',
 'adidaspuma',
 'adira',
 'adiras',
 'aditi',
 'aditya',
 'adityanath',
 'adityanaths',
 'adjourned',
 'adjournment',
 'adjustable',
 'adjusted',
 'admin',
 'administers',
 'administration',
 'administrative',
 'admission',
 'admit',
 'admits',
 'admitted',
 'adnan',
 'adobe',
 'adopt',
 'adoptable',
 'adopted',
 'adoption',
 'adopts',
 'adrenaline',
 'adult',
 'advance',
 'advanced',
 'advancing',
 'advani',
 'advanis',
 'advantage',
 'advantaged',
 'advent',
 'adventure',
 'adversity',
 'advert',
 'advertise',
 'advertisement',
 'advertising',
 'advice',
 'advise',
 'advised',
 'adviser',
 'advises',
 'advisor',
 'advisory',
 'advocate',
 'ae',
 'aengland',
 'aerial',
 'afc',
 'affair',
 'affect',
 'affected',
 'affidavit',
 'affiliation',
 'affimity',
 'affleck',
 'afflecks',
 'afford',
 'affordable',
 'afforestation',
 'afghan',
 'afghanistan',
 'afi',
 'afire',
 'afraid',
 'africa',
 'african',
 'afridi',
 'afridis',
 'afro',
 'afspa',
 'aftereffect',
 'afternoon',
 'afzal',
 'ag',
 'aga',
 'agarkar',
 'agarwal',
 'agassi',
 'age',
 'agecap',
 'aged',
 'ageing',
 'agency',
 'agenda',
 'agent',
 'agerwal',
 'aggregate',
 'aggregator',
 'aggression',
 'aggressive',
 'agitation',
 'agitator',
 'agnii',
 'agnivesh',
 'ago',
 'agp',
 'agra',
 'agrarian',
 'agrawal',
 'agree',
 'agreement',
 'agrees',
 'agri',
 'agricultural',
 'agriculture',
 'agritech',
 'agrobiodiversity',
 'agustawestland',
 'ah',
 'ahamed',
 'ahead',
 'ahil',
 'ahinda',
 'ahmad',
 'ahmed',
 'ahmedabad',
 'ahole',
 'aholes',
 'ahuja',
 'ai',
 'aiadmk',
 'aiadmks',
 'aib',
 'aiba',
 'aibased',
 'aibs',
 'aicc',
 'aid',
 'aide',
 'aiff',
 'aiims',
 'aiks',
 'ailing',
 'aim',
 'aimade',
 'aimed',
 'aimim',
 'aiming',
 'aimplb',
 'aipowered',
 'air',
 'airbag',
 'airbags',
 'airbase',
 'airbnb',
 'airbnbs',
 'airborne',
 'aircelmaxis',
 'airconditioned',
 'aircraft',
 'airdrop',
 'aire',
 'aired',
 'airfare',
 'airing',
 'airkick',
 'airlift',
 'airlifted',
 'airline',
 'airpay',
 'airplane',
 'airpods',
 'airport',
 'airship',
 'airstrike',
 'airtel',
 'airtels',
 'airticket',
 'airway',
 'airwoot',
 'aise',
 'aish',
 'aishs',
 'aishwarya',
 'aishwaryaa',
 'aishwaryas',
 'aiyar',
 'ajab',
 'ajax',
 'ajay',
 'ajit',
 'ajl',
 'ak',
 'akali',
 'akalis',
 'akbar',
 'akhilesh',
 'akhileshled',
 'akhileshs',
 'akhnoor',
 'akhtar',
 'akhtars',
 'akira',
 'akkad',
 'akmal',
 'akram',
 'akramasakrama',
 'akshay',
 'akshaye',
 'akshays',
 'akshaytwinkle',
 'alabadi',
 'aladdin',
 'aladha',
 'alaknanda',
 'alan',
 'alarm',
 'alastair',
 'alauddin',
 'alavés',
 'alba',
 'albanian',
 'albas',
 'albela',
 'albert',
 'albie',
 'album',
 'alcatel',
 'alcohol',
 'alcoholism',
 'aldrin',
 'aleksandar',
 'aleppo',
 'alert',
 'alerted',
 'alex',
 'alexander',
 'alexandre',
 'alfred',
 'algae',
 'algebra',
 'algeria',
 'algorithm',
 'ali',
 'alia',
 'alias',
 'alibaba',
 'alibabaowned',
 'alibabas',
 'alice',
 'alien',
 'aligarh',
 'align',
 'alimony',
 'alive',
 'alizeh',
 'alka',
 'alkem',
 'all',
 'allahabad',
 'allcash',
 'allegation',
 'allege',
 'alleged',
 'allegedly',
 'alleges',
 'alleging',
 'allen',
 'allglass',
 'alliance',
 'alligator',
 'allindian',
 'allocated',
 'allocates',
 'allocating',
 'allocation',
 'allot',
 'allotment',
 'allots',
 'allotted',
 'allow',
 'allowance',
 'allowed',
 'allowing',
 'allows',
 'alloy',
 'allparty',
 'allround',
 'allrounders',
 'allstock',
 'alltime',
 'allwoman',
 'allwomen',
 'ally',
 'almodovar',
 'almost',
 'alnusra',
 'alok',
 'alone',
 'along',
 'alongside',
 'alonso',
 'alp',
 'alphabet',
 'alphago',
 'alqaeda',
 'already',
 'also',
 'alta',
 'altair',
 'alter',
 'alternate',
 'alternative',
 'altitude',
 'altizon',
 'altogether',
 'aluminium',
 'aluminum',
 'alumnus',
 'alves',
 'alvida',
 'alviro',
 'always',
 'alzheimer',
 'alzheimers',
 'amal',
 'aman',
 'amanatullah',
 'amanda',
 'amar',
 'amaravati',
 'amarinder',
 'amarinders',
 'amarnath',
 'amartya',
 'amat',
 'amateur',
 'amazing',
 'amazon',
 'ambani',
 'ambanirun',
 'ambanis',
 'ambassador',
 'ambassadorial',
 'ambedkar',
 'ambedkars',
 'amber',
 'ambition',
 'ambitious',
 'ambrose',
 'ambulance',
 'ambulancehailing',
 'amend',
 'amended',
 'amendment',
 'amenity',
 'america',
 'american',
 'amethi',
 'amfar',
 'amg',
 'amicable',
 'amicus',
 'amid',
 'amir',
 'amish',
 'amit',
 'amitabh',
 'amitabhs',
 'amla',
 'amma',
 'ammas',
 'ammonia',
 'ammu',
 'ammunition',
 'amnesty',
 'among',
 'amount',
 'amour',
 'amp',
 'amphibious',
 'amputee',
 'amravati',
 'amrish',
 'amritsar',
 'amsterdam',
 'amu',
 'amuck',
 'amul',
 'amy',
 'anaarkali',
 'anabolic',
 'anaemia',
 'anaesthetic',
 'analogue',
 'analysis',
 'analytics',
 'anand',
 'ananda',
 'anandan',
 'anandiben',
 'anant',
 'ananth',
 'anantnag',
 'anarchy',
 'anatomy',
 'ancelotti',
 'ancestor',
 'ancestral',
 'anchor',
 'ancient',
 'anda',
 'andaman',
 'andaz',
 'anderson',
 'andheri',
 'andhra',
 'andhras',
 'andolan',
 'andre',
 'andrew',
 'android',
 'androidpowered',
 'andy',
 'aney',
 'ang',
 'anganwadis',
 'angel',
 'angela',
 'angeles',
 'angelina',
 'angelique',
 'anger',
 'angle',
 'angola',
 'angoori',
 'angries',
 'angry',
 'aniket',
 'anil',
 'animal',
 'animate',
 'animated',
 'animation',
 'anirban',
 'anish',
 'aniston',
 'anita',
 'anju',
 'ankara',
 'ankita',
 'ankle',
 'anna',
 'annapurna',
 'anne',
 'annex',
 'anniversary',
 'announce',
 'announced',
 'announcement',
 'announces',
 'announcing',
 'annoyed',
 'annu',
 'annual',
 'annually',
 'annulment',
 'annuls',
 'anomaly',
 'anonymity',
 'anonymous',
 'another',
 'ansari',
 'ansaris',
 'answer',
 'answerable',
 'answering',
 'antarctic',
 'antarctica',
 'antenna',
 'anthem',
 'anthony',
 'antiabortion',
 'antiageing',
 'antiaging',
 'antibegging',
 'antibiotic',
 'antibioticresistant',
 'antibjp',
 'antibody',
 'anticancer',
 'anticipate',
 'anticonversion',
 'anticorruption',
 'antidefection',
 'antidemocratic',
 'antidiabetic',
 'antidoping',
 'antidrone',
 'antidrug',
 'antidumping',
 'antiduty',
 'antiemergency',
 'antigay',
 'antigovernment',
 'antigovt',
 'antigraft',
 'antigua',
 'antiimmigration',
 'antiindia',
 'antikangana',
 'antikejriwal',
 'antilabour',
 'antiliquor',
 'antilitter',
 'antimexico',
 'antimicrobial',
 'antimigrant',
 'antimigration',
 'antimissile',
 'antimuslim',
 'antinational',
 'antinationalism',
 'antinationals',
 'antinato',
 'antinazi',
 'antipeople',
 'antipoor',
 'antiporn',
 'antipunjab',
 'antique',
 'antiradiation',
 'antiromeo',
 'antiship',
 'antisikh',
 'antismartphone',
 'antisnore',
 'antisocial',
 'antisuperstition',
 'antiterror',
 'antiterrorism',
 'antitrolling',
 'antitrump',
 'antivirus',
 'antiwar',
 'antoine',
 'antoinettes',
 'anton',
 'antonio',
 'antony',
 'antrixdevas',
 'antónio',
 'anuj',
 'anupam',
 'anupama',
 'anurag',
 'anushka',
 'anushkas',
 'anwar',
 'anxious',
 'anybody',
 'anymore',
 'anyone',
 'anyones',
 'anything',
 'anytime',
 'anywhere',
 'ap',
 'apache',
 'aparna',
 'apart',
 'apartment',
 'apathy',
 'ape',
 'apec',
 'apfel',
 'apitesting',
 'apj',
 'apna',
 'apne',
 'apocalypse',
 'apollo',
 'apologise',
 'apologised',
 'apologises',
 'apology',
 'app',
 'apparel',
 'apparelfolding',
 'appcontrolled',
 'appeal',
 'appear',
 'appearance',
 'appeared',
 'appearing',
 'appears',
 'appease',
 'appeasement',
 'appeasing',
 'appendix',
 'appetitecontrolling',
 'applauded',
 'applauds',
 'apple',
 'applicable',
 'application',
 'applied',
 'applies',
 'apply',
 'applying',
 'appoint',
 'appointed',
 'appointing',
 'appointment',
 'appoints',
 'appreciates',
 'appreciation',
 'apprentice',
 'approach',
 'approached',
 'appropriately',
 'approval',
 'approve',
 'approved',
 'approves',
 'apps',
 'apr',
 'apraug',
 'aprdec',
 'aprfeb',
 'april',
 'apriljan',
 'apriljune',
 'aprjuly',
 'aprsep',
 'aprsept',
 'apsez',
 'apt',
 'apte',
 'aptes',
 'aqua',
 'ar',
 'arabia',
 'arabian',
 'arabic',
 'aramco',
 'arbaaz',
 'arbitration',
 'arcelormittalsail',
 'archaeologist',
 'archbishop',
 'architecture',
 'archive',
 'archived',
 'archivist',
 'arctic',
 'area',
 'arena',
 'arent',
 'argentina',
 'argue',
 'argument',
 'arhar',
 'ariana',
 'arianna',
 'arijit',
 'aristotle',
 'arizona',
 'arjun',
 'arjuna',
 'arjuns',
 'arm',
 'armband',
 'armed',
 'armoured',
 'armpit',
 'armwrestle',
 'army',
 'arnab',
 'arnold',
 'arora',
 'around',
 'aroundthenet',
 'arrange',
 'arrangement',
 'arrears',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arrogant',
 'arsenal',
 'arshad',
 'arshads',
 'arshi',
 'art',
 'artefact',
 'arthur',
 'article',
 'artificial',
 'artillery',
 'artist',
 'artiste',
 'artistic',
 'arun',
 'arunabh',
 'arunachal',
 'arunachals',
 'arundhati',
 'arunoday',
 'arup',
 'arvind',
 'aryan',
 'as',
 'asad',
 'asaduddin',
 'asafa',
 'ascetic',
 'asghar',
 'ash',
 'asha',
 'ashamed',
 'asheslike',
 'ashok',
 'ashraf',
 'ashram',
 'ashton',
 'ashutosh',
 'ashutoshs',
 'ashwin',
 'ashwins',
 'asia',
 'asian',
 'asiatic',
 'aside',
 'ask',
 'asked',
 'asking',
 'askme',
 'askmes',
 'asks',
 'aslams',
 'asleep',
 'asli',
 'aspiration',
 'aspirational',
 'ass',
 'assad',
 'assailant',
 'assam',
 'assamese',
 'assange',
 'assanges',
 'assassin',
 'assassination',
 'assault',
 'assaulted',
 'assaulting',
 'assembling',
 'assembly',
 'assessed',
 'asset',
 'assi',
 'assist',
 'assistance',
 'assistant',
 'assistedliving',
 'assocham',
 'associate',
 'associated',
 'association',
 'assume',
 'assumed',
 'assure',
 'assured',
 'assures',
 'asteroid',
 'asteroidsample',
 'asthmatracking',
 'aston',
 'astro',
 'astronaut',
 'astronomer',
 'asus',
 'asylum',
 'atal',
 'atalji',
 'atampt',
 'atampttime',
 'atauro',
 'atcviom',
 'athawale',
 'atheist',
 'atherton',
 'athlete',
 'athletics',
 'atif',
 'atlanta',
 'atlantic',
 'atlas',
 'atletico',
 'atlético',
 'atm',
 'atma',
 'atmosphere',
 'atmospheric',
 'atom',
 'atomic',
 'atomsized',
 'atop',
 'atp',
 'atrociously',
 'atrocity',
 'attache',
 'attached',
 'attachment',
 'attack',
 'attacked',
 'attacker',
 'attacking',
 ...]

In [23]:
train_df_frist = pd.DataFrame(train_tf_first.toarray(),columns = tf.get_feature_names())

In [24]:
train_df_frist

,aa,aadat,aadhaar,aadhaarlinked,aadmi,aag,aah,aahaa,aaina,aaj,...,zoya,zubaan,zubeen,zuckerberg,zuckerbergbacked,zuckerbergs,zzungry,ºc,émon,शभक
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16877,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
y_train.shape

(16881,)

In [26]:
test_df_first = pd.DataFrame(tf.transform(X_test).toarray(),columns = tf.get_feature_names())

In [27]:
test_df_first

,aa,aadat,aadhaar,aadhaarlinked,aadmi,aag,aah,aahaa,aaina,aaj,...,zoya,zubaan,zubeen,zuckerberg,zuckerbergbacked,zuckerbergs,zzungry,ºc,émon,शभक
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8311,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8312,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8313,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8314,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
y_test.shape

(8315,)

In [29]:
examine = train_df_frist.iloc[1]

In [30]:
examine.sort_values(ascending=False)

recognition    0.516540
stock          0.457849
exchange       0.444118
cancel         0.431002
delhi          0.297251
                 ...
philosophy     0.000000
phillip        0.000000
phillauri      0.000000
philippine     0.000000
aa             0.000000
Name: 1, Length: 15289, dtype: float64

In [31]:
y_train[1]

1.0

In [32]:
X2 = df['Short_lemma']

In [33]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y, test_size=0.33, random_state=42)

In [34]:
tf2= TfidfVectorizer()

In [35]:
tf2.fit(X_train2)

TfidfVectorizer()

In [36]:
train_tf_second = tf2.transform(X_train2)

In [37]:
train_df_second = pd.DataFrame(train_tf_second.toarray(),columns = tf2.get_feature_names())

In [38]:
train_df_second.head(5)

,aa,aadat,aadhaar,aadhaarlinked,aadhaars,aadhar,aadmi,aadukalam,aag,aage,...,दव,नरस,नह,पर,पहलव,रक,वगन,शभक,सकत,सत
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
train_df_second.shape

(16881, 38879)

In [40]:
y_train2.shape

(16881,)

In [42]:
test_df_second = pd.DataFrame(tf2.transform(X_test2).toarray(),columns = tf2.get_feature_names())

In [43]:
test_df_second.shape

(8315, 38879)

In [44]:
y_test2.shape

(8315,)

In [45]:
pwd

'C:\\Users\\admin\\Downloads\\Capstone Project - Inshorts'